// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function ProcessCSVData(arg1:string):Promise<string>;

export function UpdateConfig(arg1:main.Config):Promise<void>;
